fileVersion: 1
id: "27"
mappingDefinitions:
  DESTINATION:
    database: BEN_EDW
    schema: invalid
  SOURCE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
name: COA Environment
type: Environment
